clinical_data = [{"source_column": "del5q"},
                 {"source_column": "Lossofchr5ordel5qPLUSother"},
                 {"source_column": "Lossofchr7ordel7q"},
                 {"source_column": "Gainofchr8"},
                 {"source_column": "Lossofchr9ordel9q"},
                 {"source_column": "Lossofchr11ordel11q"},
                 {"source_column": "Lossofchr12ordel12port12p"},
                 {"source_column": "Lossofchr13ordel13q"},
                 {"source_column": "Isochr17qort17p"},
                 {"source_column": "Lossofchr20ordel20q"},
                 {"source_column": "LossofchrY"},
                 {"source_column": "idicXq13"},
                 {"source_column": "AOD"},
                 {"source_column": "RS"},
                 {"source_column": "Neutrophils"},
                 {"source_column": "Hemoglobin"},
                 {"source_column": "Platelets"},
                 {"source_column": "LDH"},
                 {"source_column": "Ferritin"},
                 {"source_column": "BMB"},
                 {"source_column": "BMMD"},
                 {"source_column": "BMF"}]
demographics_data = [{"source_column": "Patient ID", "variable_name": "patient_id"},
                     {"source_column": "Gender", "variable_name": "patient_gender"}]
observation_data = [{"source_column": "Neutrophils"},
                    {"source_column": "Hemoglobin"},
                    {"source_column": "Platelets"},
                    {"source_column": "LDH"},
                    {"source_column": "Ferritin"}]
conditions_data = [{"source_column": "del5q"},
                   {"source_column": "Lossofchr5ordel5qPLUSother"},
                   {"source_column": "Lossofchr7ordel7q"},
                   {"source_column": "Gainofchr8"},
                   {"source_column": "Lossofchr9ordel9q"},
                   {"source_column": "Lossofchr11ordel11q"},
                   {"source_column": "Lossofchr12ordel12port12p"},
                   {"source_column": "Lossofchr13ordel13q"},
                   {"source_column": "Isochr17qort17p"},
                   {"source_column": "Lossofchr20ordel20q"},
                   {"source_column": "LossofchrY"},
                   {"source_column": "idicXq13"},
                   {"source_column": "AOD"},
                   {"source_column": "RS"},
                   {"source_column": "BMB"},
                   {"source_column": "BMMD"},
                   {"source_column": "BMF"}]
